---
name: POE-Component-IRC-Plugin-WWW-OhNoRobotCom-Search
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: search http://ohnorobot.com/ website from IRC
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE::Component::IRC::Plugin::BasePoCoWrap: 0.002
  POE::Component::WWW::OhNoRobotCom::Search: 0.001
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::WWW::OhNoRobotCom::Search:
    file: lib/POE/Component/IRC/Plugin/WWW/OhNoRobotCom/Search.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
